#!/bin/bash

source include/functions
source include/prepare
source include/ver
source include/l10n-EN

####### Start builds of packages #######

# kerberos is a complicated build. Do I really need it now?
# source $SCRIPTS_DIR/kerberos

source $SCRIPTS_DIR/openssl
source $SCRIPTS_DIR/cacert
source $SCRIPTS_DIR/curl
source $SCRIPTS_DIR/standard-build wget
source $SCRIPTS_DIR/sqlite
source $SCRIPTS_DIR/tcl tcl
source $SCRIPTS_DIR/tcl tk
source $SCRIPTS_DIR/standard-build python
source $SCRIPTS_DIR/setuptools
source $SCRIPTS_DIR/pip
source $SCRIPTS_DIR/virtualenv
source $SCRIPTS_DIR/ipython
# atlas will install lapack
# source $SCRIPTS_DIR/lapack
# numpy wants atlas
# Giving up on atlas and lapack which need lots of modern stuff like Fortran 95
# source $SCRIPTS_DIR/atlas
source $SCRIPTS_DIR/numpy
# see TODO for matplotlib build
# source $SCRIPTS_DIR/pip-install matplotlib
# source $SCRIPTS_DIR/pip-install pandas
# source $SCRIPTS_DIR/pip-install scipy
source $SCRIPTS_DIR/perl
source $SCRIPTS_DIR/standard-build asciidoc
# TODO: git isn't installing manuals
source $SCRIPTS_DIR/standard-build git
source $SCRIPTS_DIR/vim

echo "Success"
echo "To start over from scratch, run like:"
echo "    REBUILD_ALL=1 ./makeall"
echo ""
echo "To rebuild from a single package ... I dont know how to do that yet"
