#!/bin/bash

NAME=lib/libagg.a
PROGRAM=agg-2.5
FILE=agg-2.5.tar.gz
EXT=gzip
DLINK=http://www.antigrain.com/agg-2.5.tar.gz
MD5=0229a488bc47be10a2fee6cf0b2febd6

if [ $REBUILD_ALL ]; then
    echo Building $PREFIX32/$NAME because REBUILD_ALL=$REBUILD_ALL
elif [ -e $PREFIX32/$NAME ]; then
    echo Skipping $PREFIX32/$NAME because we already have it
    return
else
    echo Building $PREFIX32/$NAME because dont have it yet
fi

check_quiet ${FILE} ${MD5}

if [ $? -eq 0 ]; then
	download ${DLINK}

	waitUser

	check ${FILE} ${MD5}

	waitUser
fi

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	sh autogen.sh
	./configure --prefix=$PREFIX32 || exit 1
	StartMake
	waitUser
	make || exit 1
	waitUser
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
cd $ROOT
