#!/bin/bash

NAME=${cacert[0]}
PROGRAM=${cacert[3]}
FILE=${cacert[2]}
EXT=${cacert[4]}
DLINK=${cacert[1]}
MD5=${cacert[5]}

if [ $REBUILD_ALL ]; then
    echo Building $PREFIX32/$NAME because REBUILD_ALL=$REBUILD_ALL
elif [ -e $PREFIX32/$NAME ]; then
    echo Skipping $PREFIX32/$NAME because we already have it
    return
else
    echo Building $PREFIX32/$NAME because dont have it yet
fi

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	cp $SCRIPTS_DIR/cacert-scripts/* ./ || exit 1
	cp "certdata.txt?raw=1" certdata.txt
	./make-ca.sh || exit 1
	./remove-expired-certs.sh certs
	SSLDIR=$PREFIX32/ssl
	install -d $SSLDIR/certs || exit 1
	cp -v certs/*.pem $SSLDIR/certs || exit 1
	c_rehash || exit 1
	install BLFS-ca-bundle*.crt $SSLDIR/ca-bundle.crt || exit 1
	ln -sv ../ca-bundle.crt $SSLDIR/certs/ca-certificates.crt
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
cd $ROOT
