#!/bin/bash

NAME=lib/python2.7/site-packages/matplotlib
PROGRAM=matplotlib

if [ $REBUILD_ALL ]; then
    echo Building $PREFIX32/$NAME because REBUILD_ALL=$REBUILD_ALL
elif [ -e $PREFIX32/$NAME ]; then
    echo Skipping $PREFIX32/$NAME because we already have it
    return
else
    echo Building $PREFIX32/$NAME because dont have it yet
fi

# These environment variables disable some difficult-to-build dependencies.
# This may cause a problem like missing numpy functionality or poor
# performance. I don't really understand it. This does get it to fucking build
# though.
export ATLAS=None
export BLAS=None
export LAPACK=None

# Fix bug where it can't find freetype header
export CFLAGS="${CFLAGS} -I/usr/include/freetype2 "

rm -Rf $BUILD_DIR/$PROGRAM || exit 1
mkdir -p $BUILD_DIR/$PROGRAM || exit 1
cd $BUILD_DIR/$PROGRAM
{
    if [ $REBUILD_ALL ]; then
        pip reinstall $PROGRAM || exit 1
    else
        pip install $PROGRAM || exit 1
    fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
cd $ROOT
