#!/bin/bash

NAME=lib/python2.7/site-packages/matplotlib
PROGRAM=matplotlib
DLINK=https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.3.0/matplotlib-1.3.0.tar.gz
MD5=139e1157a3e641fa6270d667a2088458  matplotlib-1.3.0.tar.gz
EXT=gzip

if [ $REBUILD_ALL ]; then
    echo Building $PREFIX32/$NAME because REBUILD_ALL=$REBUILD_ALL
elif [ -e $PREFIX32/$NAME ]; then
    echo Skipping $PREFIX32/$NAME because we already have it
    return
else
    echo Building $PREFIX32/$NAME because dont have it yet
fi

# These environment variables disable some difficult-to-build dependencies.
# This may cause a problem like missing numpy functionality or poor
# performance. I don't really understand it. This does get it to fucking build
# though.
export ATLAS=None
export BLAS=None
export LAPACK=None

# Fix bug where it can't find freetype header
export CFLAGS="${CFLAGS} -I/usr/include/freetype2 "

# Download matplotlib
check_quiet ${FILE} ${MD5}

if [ $? -eq 0 ]; then
	download ${DLINK}

	waitUser

	check ${FILE} ${MD5}

	waitUser
fi

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
    cp setup.cfg.template setup.cfg
    sed -i setup.cfg "s/.*basedirlist/basedirlist = ${PREFIX},/usr"
    if [ $REBUILD_ALL ]; then
        python setup.py reinstall
    else
        python setup.py install
    fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
cd $ROOT
