#!/bin/bash

NAME=${vim[0]}
PROGRAM=${vim[3]}
FILE=${vim[2]}
EXT=${vim[4]}
DLINK=${vim[1]}
MD5=${vim[5]}

if [ $REBUILD_ALL ]; then
    echo Building $PREFIX32/$NAME because REBUILD_ALL=$REBUILD_ALL
elif [ -e $PREFIX32/$NAME ]; then
    echo Skipping $PREFIX32/$NAME because we already have it
    return
else
    echo Building $PREFIX32/$NAME because dont have it yet
fi

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild
cd $BUILD_DIR/$PROGRAM
{
# --enable-luainterp  
	./configure --prefix=${PREFIX32} --with-features=huge --enable-pythoninterp --enable-perlinterp --enable-tclinterp || exit 1
    sed -i src/auto/config.mk "s:-lieee: :"
	StartMake
	waitUser
	make || exit 1
	waitUser
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
cd $ROOT
